repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: Ruff - Lint
        entry: ruff check --force-exclude --fix
        language: system
        types_or: [python, pyi]
        require_serial: true

      - id: ruff-format
        name: Ruff - Format code
        entry: ruff format --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
