name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  pre-commit-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies (including dev)
        run: poetry install --with dev

      - name: Install pre-commit hooks
        run: poetry run pre-commit install --install-hooks

      - name: Run pre-commit on all files
        run: poetry run pre-commit run --all-files

      - name: Run ruff lint (separate explicit check)
        run: poetry run ruff check --force-exclude .
